branches:
  only:
    - master
    - v1
    - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
language: go
go: 1.13.x
os:
  - osx
  - linux
cache:
  - directories:
      - "$GOPATH/bin"
      - "$GOPATH/pkg"
      - "$PWD/tmp"
script:
  - make bootstrap
  - make lint
  - make test